// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fsutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_unarc_cpio extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __obj_src;
	private system.proxies.FileDocument obj_src;

	public ja_unarc_cpio(IContext context, IMendixObject obj_src)
	{
		super(context);
		this.__obj_src = obj_src;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.obj_src = __obj_src == null ? null : system.proxies.FileDocument.initialize(getContext(), __obj_src);

		// BEGIN USER CODE
		return this.uncpio(
			obj_src.getMendixObject(),
			this.getContext(),
			true,
			"System.FileDocuemnt"
		);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_unarc_cpio";
	}

	// BEGIN EXTRA CODE
        private java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> uncpio(
		com.mendix.systemwideinterfaces.core.IMendixObject obj_filedocument,
		com.mendix.systemwideinterfaces.core.IContext ctx,
		java.lang.Boolean txn,
		java.lang.String objType
	){
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> ret=new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
		/*
		txn=txn==null?false:txn;
		objType=objType==null?"System.FileDocument":objType;
		com.mendix.systemwideinterfaces.core.IContext _ctx=ctx;
		java.io.InputStream is=com.mendix.core.Core.getFileDocumentContent(ctx,obj_filedocument);
		org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream cpiois=new org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream(is);
		try{
			org.apache.commons.compress.archivers.ArchiveEntry tent=cpiois.getNextCpioEntry();            
			while(tent!=null){
				try{
					if(!tent.isDirectory()){
						java.io.ByteArrayOutputStream baos=new java.io.ByteArrayOutputStream();
						org.apache.commons.io.IOUtils.copy(cpiois,baos);
						java.io.InputStream bais=new java.io.ByteArrayInputStream(baos.toByteArray());
						if(txn)_ctx=ctx.getSession().createContext();
						if(txn)_ctx.startTransaction();
						com.mendix.systemwideinterfaces.core.IMendixObject o=com.mendix.core.Core.instantiate(_ctx,objType);
						o.setValue(_ctx,"Name",tent.getName());
						com.mendix.core.Core.storeFileDocumentContent(_ctx,o,bais);
						if(txn)com.mendix.webui.FeedbackHelper.addRefreshObjectFeedback(_ctx,o.getId());
						if(txn)_ctx.endTransaction();
						ret.add(o);					        
					}
				}catch(Exception e){
					com.mendix.core.Core.getLogger(this.toString()).error(e);
				}                
				tent=cpiois.getNextCpioEntry();            
			}
			cpiois.close(); 
		}catch(Exception e){
			com.mendix.core.Core.getLogger(this.toString()).error(e);
		}
		*/
		return ret;
        }        

	// END EXTRA CODE
}
