// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scenegraph.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ja_sin extends CustomJavaAction<java.lang.Double>
{
	private java.lang.Double a;

	public ja_sin(IContext context, java.lang.Double a)
	{
		super(context);
		this.a = a;
	}

	@java.lang.Override
	public java.lang.Double executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Math.sin(a);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_sin";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
