// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package scenegraph.proxies;

public class Bezier extends scenegraph.proxies.Primitive
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SceneGraph.Bezier";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nbPoints("nbPoints"),
		Name("Name"),
		x("x"),
		y("y"),
		z("z"),
		rotx("rotx"),
		roty("roty"),
		rotz("rotz"),
		sclx("sclx"),
		scly("scly"),
		sclz("sclz"),
		color("color"),
		visible("visible"),
		opacity("opacity"),
		Primitive_Node("SceneGraph.Primitive_Node"),
		Selected("SceneGraph.Selected"),
		Texture("SceneGraph.Texture");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Bezier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SceneGraph.Bezier"));
	}

	protected Bezier(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bezierMendixObject)
	{
		super(context, bezierMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SceneGraph.Bezier", bezierMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SceneGraph.Bezier");
	}

	/**
	 * @deprecated Use 'Bezier.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static scenegraph.proxies.Bezier initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return scenegraph.proxies.Bezier.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static scenegraph.proxies.Bezier initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new scenegraph.proxies.Bezier(context, mendixObject);
	}

	public static scenegraph.proxies.Bezier load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return scenegraph.proxies.Bezier.initialize(context, mendixObject);
	}

	public static java.util.List<scenegraph.proxies.Bezier> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<scenegraph.proxies.Bezier> result = new java.util.ArrayList<scenegraph.proxies.Bezier>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SceneGraph.Bezier" + xpathConstraint))
			result.add(scenegraph.proxies.Bezier.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of nbPoints
	 */
	public final java.lang.Integer getnbPoints()
	{
		return getnbPoints(getContext());
	}

	/**
	 * @param context
	 * @return value of nbPoints
	 */
	public final java.lang.Integer getnbPoints(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.nbPoints.toString());
	}

	/**
	 * Set value of nbPoints
	 * @param nbpoints
	 */
	public final void setnbPoints(java.lang.Integer nbpoints)
	{
		setnbPoints(getContext(), nbpoints);
	}

	/**
	 * Set value of nbPoints
	 * @param context
	 * @param nbpoints
	 */
	public final void setnbPoints(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nbpoints)
	{
		getMendixObject().setValue(context, MemberNames.nbPoints.toString(), nbpoints);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final scenegraph.proxies.Bezier that = (scenegraph.proxies.Bezier) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SceneGraph.Bezier";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
