// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package scenegraph.proxies;

public class Torus extends scenegraph.proxies.Primitive
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SceneGraph.Torus";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		d("d"),
		thickness("thickness"),
		tessellation("tessellation"),
		doublesided("doublesided"),
		Name("Name"),
		x("x"),
		y("y"),
		z("z"),
		rotx("rotx"),
		roty("roty"),
		rotz("rotz"),
		sclx("sclx"),
		scly("scly"),
		sclz("sclz"),
		color("color"),
		visible("visible"),
		Primitive_Node("SceneGraph.Primitive_Node"),
		Selected("SceneGraph.Selected"),
		Texture("SceneGraph.Texture");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Torus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SceneGraph.Torus"));
	}

	protected Torus(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject torusMendixObject)
	{
		super(context, torusMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SceneGraph.Torus", torusMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SceneGraph.Torus");
	}

	/**
	 * @deprecated Use 'Torus.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static scenegraph.proxies.Torus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return scenegraph.proxies.Torus.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static scenegraph.proxies.Torus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new scenegraph.proxies.Torus(context, mendixObject);
	}

	public static scenegraph.proxies.Torus load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return scenegraph.proxies.Torus.initialize(context, mendixObject);
	}

	public static java.util.List<scenegraph.proxies.Torus> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<scenegraph.proxies.Torus> result = new java.util.ArrayList<scenegraph.proxies.Torus>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SceneGraph.Torus" + xpathConstraint))
			result.add(scenegraph.proxies.Torus.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of d
	 */
	public final java.lang.Double getd()
	{
		return getd(getContext());
	}

	/**
	 * @param context
	 * @return value of d
	 */
	public final java.lang.Double getd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.d.toString());
	}

	/**
	 * Set value of d
	 * @param d
	 */
	public final void setd(java.lang.Double d)
	{
		setd(getContext(), d);
	}

	/**
	 * Set value of d
	 * @param context
	 * @param d
	 */
	public final void setd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double d)
	{
		getMendixObject().setValue(context, MemberNames.d.toString(), d);
	}

	/**
	 * @return value of thickness
	 */
	public final java.lang.Double getthickness()
	{
		return getthickness(getContext());
	}

	/**
	 * @param context
	 * @return value of thickness
	 */
	public final java.lang.Double getthickness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.thickness.toString());
	}

	/**
	 * Set value of thickness
	 * @param thickness
	 */
	public final void setthickness(java.lang.Double thickness)
	{
		setthickness(getContext(), thickness);
	}

	/**
	 * Set value of thickness
	 * @param context
	 * @param thickness
	 */
	public final void setthickness(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double thickness)
	{
		getMendixObject().setValue(context, MemberNames.thickness.toString(), thickness);
	}

	/**
	 * @return value of tessellation
	 */
	public final java.lang.Double gettessellation()
	{
		return gettessellation(getContext());
	}

	/**
	 * @param context
	 * @return value of tessellation
	 */
	public final java.lang.Double gettessellation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.tessellation.toString());
	}

	/**
	 * Set value of tessellation
	 * @param tessellation
	 */
	public final void settessellation(java.lang.Double tessellation)
	{
		settessellation(getContext(), tessellation);
	}

	/**
	 * Set value of tessellation
	 * @param context
	 * @param tessellation
	 */
	public final void settessellation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double tessellation)
	{
		getMendixObject().setValue(context, MemberNames.tessellation.toString(), tessellation);
	}

	/**
	 * @return value of doublesided
	 */
	public final java.lang.Boolean getdoublesided()
	{
		return getdoublesided(getContext());
	}

	/**
	 * @param context
	 * @return value of doublesided
	 */
	public final java.lang.Boolean getdoublesided(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.doublesided.toString());
	}

	/**
	 * Set value of doublesided
	 * @param doublesided
	 */
	public final void setdoublesided(java.lang.Boolean doublesided)
	{
		setdoublesided(getContext(), doublesided);
	}

	/**
	 * Set value of doublesided
	 * @param context
	 * @param doublesided
	 */
	public final void setdoublesided(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean doublesided)
	{
		getMendixObject().setValue(context, MemberNames.doublesided.toString(), doublesided);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final scenegraph.proxies.Torus that = (scenegraph.proxies.Torus) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SceneGraph.Torus";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
